name: 每日發送匯率訊息

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取 Repo 原始碼
      uses: actions/checkout@v3
    
    - name: 安裝 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 安裝套件
      run: pip install requests pandas
    
    - name: 執行匯率程式
      run: python forex_bot.py
      env:
        TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
        TG_CHAT_ID: ${{secrets.TG_CHAT_ID}}
